version: '2'

jobs:

  python2-test:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run: |
          sudo pip install -r requires/testing.txt codecov
          nosetests --with-coverage
          codecov

  python3-test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: |
          sudo pip install -r requires/testing.txt codecov
          nosetests --with-coverage
          codecov

workflows:
  version: 2
  build-workflow:
      jobs:
        - python2-test
        - python3-test
